services:
  app:
    build:
      context: docker/php
      dockerfile: Dockerfile.dev
    volumes:
      - ./symfony:/app
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000 -t public
    environment:
      APP_ENV: dev
