services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.dev
    volumes:
      - ./symfony:/app
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000 -t public
    environment:
      APP_ENV: dev
      XDEBUG_MODE: debug,coverage
    depends_on:
      - db
  vue:
    build:
      context: .
      dockerfile: docker/vue/Dockerfile.dev
    volumes:
      - ./vue:/app
    ports:
      - "5173:5173"
    depends_on:
      - db
      - php
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: job_applications
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U symfony -d job_applications"]
      interval: 30s
      timeout: 10s
      retries: 10
